Code review error correction
Rashad-Muntar/NEWS-WEEK-CLONE pull request #4
Opened 2021-01-30 00:11 UTC by Rashad-Muntar

* Corrected  all linter errors.
 * README live preview link is updated
 * Remove unnecessary repo style2.css and style.map.css from repo
 * Image now displaying
 * Elements margin are ven on mobile view
 * distorted image now resolved
 * Subscribe and Newsletter matches with original layout
 *  Text not overlaping on tablet view
 * editors pick should shows two column layout on tablet view
 * Changed all necessary bootstrap css element

2021-01-30 03:25 UTC, voscarmv requested changes
# Impressive work, team. 💻 👀 ✨ 

## However, there are some changes required 👀 🧰 🔨 🔧 
- There are still problems with images becoming stretched and distorted while resizing the page. Also, there are problems with the position of image tags. Please fix them:
![image](https://user-images.githubusercontent.com/2739245/106345488-2f0d5d00-6276-11eb-859b-ca053b7b409a.png)

![image](https://user-images.githubusercontent.com/2739245/106345502-46e4e100-6276-11eb-901c-2cd003e865b4.png)

![image](https://user-images.githubusercontent.com/2739245/106345509-595f1a80-6276-11eb-88aa-c455dd993ac3.png)

- In tablet and mobile views the page overflows to the side. Please fix your page so there is no horizontal scrolling here:

![image](https://user-images.githubusercontent.com/2739245/106345554-b78bfd80-6276-11eb-9ca6-6992c83da0f8.png)

- Please replace all instances of `flex` in your CSS with bootstrap. Your CSS should not contain any references to flex.
![image](https://user-images.githubusercontent.com/2739245/106345815-7c8ac980-6278-11eb-95f4-e358d2bd13f9.png)

### Submit these changes and request a new code review! 😄 👍 

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

2021-01-30 13:05 UTC, BrittanyBlake requested changes
### Status: Changes Required ♻️ 
****
### Hi @Rashad-Muntar! 👋 
Great job working on the requested changes!👏 👏 👏  There are just a few issues that need to be resolved before you can move on: ⬇️ 
****
### General
- [ ] You are using a lot of css styling that can be done with bootstrap classes. Please take a look at this [cheat sheet](https://hackerthemes.com/bootstrap-cheatsheet/) and see what rules you can replace with bootstrap classes. 
### Mobile

- [ ] Some of your image labels are distorted on the mobile screen 
Your clone 👇🏾 
![Screen Shot 2021-01-30 at 1 58 42 PM](https://user-images.githubusercontent.com/48804258/106356915-43e40200-6303-11eb-8694-2fdabb077f23.png)
![Screen Shot 2021-01-30 at 1 58 51 PM](https://user-images.githubusercontent.com/48804258/106356918-49414c80-6303-11eb-894d-bc13f133b50f.png)

The original page 👇🏾 
![Screen Shot 2021-01-30 at 1 59 15 PM](https://user-images.githubusercontent.com/48804258/106356929-578f6880-6303-11eb-95de-7691a66f51ea.png)
![Screen Shot 2021-01-30 at 1 59 30 PM](https://user-images.githubusercontent.com/48804258/106356938-60803a00-6303-11eb-8009-8ec4454e6e44.png)

### Tablet

- [ ] The image label on the featured stories image isn't formatted properly
Your clone 👇🏾 
![Screen Shot 2021-01-30 at 2 01 07 PM](https://user-images.githubusercontent.com/48804258/106356972-9a514080-6303-11eb-86bb-1ca42fc6dc8a.png)
The original page 👇🏾 
![Screen Shot 2021-01-30 at 2 01 24 PM](https://user-images.githubusercontent.com/48804258/106356978-a4733f00-6303-11eb-9844-e78b286d0b0d.png)

- [ ] The copyright text on your footer appears to be wrapping over into the next line instead of staying on one line
Your clone 👇🏾 
![Screen Shot 2021-01-30 at 2 02 52 PM](https://user-images.githubusercontent.com/48804258/106357015-d8e6fb00-6303-11eb-8312-6df6c8c06b42.png)
The original page 👇🏾 
![Screen Shot 2021-01-30 at 2 03 05 PM](https://user-images.githubusercontent.com/48804258/106357020-e13f3600-6303-11eb-9666-0482a446d404.png)
### Desktop
- [ ] The image label on the featured stories image isn't formatted properly
Your clone 👇🏾 
![Screen Shot 2021-01-30 at 2 05 05 PM](https://user-images.githubusercontent.com/48804258/106357069-282d2b80-6304-11eb-85d5-6f0255fddfaf.png)

- See my comments below for additional changes


****
Good Luck and Happy Coding 🍀 👩🏾‍💻

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Brittany Blake)._

2021-01-30 13:05 UTC, BrittanyBlake commented on style.css
> +}
- [ ] This can be done with the bootstrap classes `text-decoration-none` and `text-white`

2021-01-30 13:05 UTC, BrittanyBlake commented on style.css
> +}
- [ ] This can be done with bootstrap classes

2021-01-30 13:05 UTC, BrittanyBlake commented on style.css
> +}
- [ ] This can be done with the bootstrap classes `d-none` and `d-block`

2021-01-30 13:05 UTC, BrittanyBlake commented on style.css
> +  display: none;
- [ ] This can be done with bootstrap classes

2021-01-30 13:05 UTC, BrittanyBlake commented on style.css
> +  display: none;
- [ ] This can be done with bootstrap classes.

2021-01-30 13:05 UTC, BrittanyBlake commented on style.css
> +}
- [ ] This can be done with the bootstrap classes `justify-content-center` and `align-items-center`

2021-01-30 13:05 UTC, BrittanyBlake commented on style.css
> +  text-decoration: none;
- [ ] This can be done with bootstrap classes

2021-01-30 13:05 UTC, BrittanyBlake commented on style.css
> +  text-decoration: none;
- [ ] This can be done with bootstrap classes

2021-01-30 13:05 UTC, BrittanyBlake commented on style.css
> +  align-items: center;
- [ ] This can be done with bootstrap classes

2021-01-30 13:05 UTC, BrittanyBlake commented on style.css
> +}
- [ ] This can be done with bootstrap classes

2021-01-30 13:05 UTC, BrittanyBlake commented on style.css
> +  justify-content: flex-start;
- [ ] This can be done with the bootstrap class `justify-content-start`

2021-01-30 13:05 UTC, BrittanyBlake commented on style.css
> +}
- [ ] This can be done with the bootstrap class `border-0`

2021-01-30 13:05 UTC, BrittanyBlake commented on style.css
> +}
- [ ] This can be done with the bootstrap class `p-0`

2021-01-30 13:05 UTC, BrittanyBlake commented on style.css
> +}
- [ ] This can be done with bootstrap classes

2021-01-30 13:05 UTC, BrittanyBlake commented on style.css
> +}
- [ ] This can be done with bootstrap classes

2021-01-30 13:05 UTC, BrittanyBlake commented on style.css
> +}
- [ ] This can be done with bootstrap classes

2021-01-30 13:05 UTC, BrittanyBlake commented on style.css
> +}
- [ ] This can be done with bootstrap classes

2021-01-30 13:05 UTC, BrittanyBlake commented on style.css
> +  color: black;
- [ ] This can be done with bootstrap classes

2021-01-30 13:05 UTC, BrittanyBlake commented on style.css
> +}
- [ ] This can be done with the bootstrap class `h-100`

2021-01-30 13:05 UTC, BrittanyBlake commented on style.css
> +  padding: 0;
- [ ] This can be done with the bootstrap classes `m-0` and `p-0`

2021-01-30 13:05 UTC, BrittanyBlake commented on style.css
> +  text-align: center;
- [ ] This can be done with the bootstrap class `text-center`

2021-01-30 13:05 UTC, BrittanyBlake commented on style.css
> +  text-align: center;
- [ ] This can be done with bootstrap classes

2021-01-30 13:05 UTC, BrittanyBlake commented on style.css
> +}
- [ ] This can be done with bootstrap classes

2021-01-30 13:05 UTC, BrittanyBlake commented on style.css
> +}
- [ ] This can be done with bootstrap classes

2021-01-30 13:05 UTC, BrittanyBlake commented on style.css
> +  border-bottom: 1px solid lightgray;
- [ ] This can be done with bootstrap classes

2021-01-30 13:05 UTC, BrittanyBlake commented on style.css
> +}
- [ ] This can be done with bootstrap classes

2021-01-30 13:05 UTC, BrittanyBlake commented on style.css
> +}
- [ ] This can be done with bootstrap classes

2021-01-30 13:05 UTC, BrittanyBlake commented on style.css
> +  }
- [ ] This can be done with the bootstrap class `d-*-none` (`d-sm-none`/`d-md-none`/`d-lg-none`/`d-xl-none`)

2021-01-30 13:05 UTC, BrittanyBlake commented on style.css
> +  }
- [ ] This can be done with bootstrap classes

2021-01-30 13:05 UTC, BrittanyBlake commented on style.css
> +  }
- [ ] This can be done with bootstrap classes

2021-01-30 13:05 UTC, BrittanyBlake commented on style.css
> +  }
- [ ] This can be done with bootstrap classes

2021-01-30 13:05 UTC, BrittanyBlake commented on style.css
> +  }
- [ ] This can be done with bootstrap classes

2021-01-30 13:05 UTC, BrittanyBlake commented on style.css
> +  }
- [ ] This can be done with the bootstrap class `order-*-#` (`order-1`/ `order-sm-1`/ `order-md-2`/`order-lg-3`)

2021-01-30 13:05 UTC, BrittanyBlake commented on style.css
> +    justify-content: flex-start !important;
- [ ] Try not to use important in your css file if it can be avoided. This can be done with the bootstrap classes `justify-content-sm-start` and `align-items-sm-start`

2021-01-30 13:05 UTC, BrittanyBlake commented on style.css
> +    width: 100%;
- [ ] This can be done with bootstrap classes

2021-01-30 20:50 UTC, BrittanyBlake approved these changes
### Status: Approved ✅ 
****
### Hi @Rashad-Muntar! 👋 
### Great job implementing the requested changes!! 🎖️ It's a 👍 from me! Go ahead and merge this pull request and keep up the good work 😄
****

 Good Luck and Happy Coding! 🍀 👩🏾‍💻

2021-01-31 23:03 UTC, merged

2021-02-05 16:31 UTC, Spayco reviewed
# Project Approved ✔️ 

your project is now approved! (Milestone 1)


Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_